import type { ComponentType } from 'react'
import {
  AlarmClock,
  Archive,
  Armchair,
  BanknoteArrowUp,
  Baby,
  BadgeDollarSign,
  Bath,
  BedDouble,
  Beer,
  BellRing,
  Bike,
  Bolt,
  BriefcaseBusiness,
  BookOpen,
  Building2,
  BusFront,
  Camera,
  CalendarDays,
  CarFront,
  Cigarette,
  ChartNoAxesCombined,
  ChartPie,
  ChefHat,
  CircleDollarSign,
  CircleGauge,
  CirclePlus,
  Clapperboard,
  ClipboardList,
  CloudSun,
  Coins,
  Coffee,
  CookingPot,
  CreditCard,
  Crown,
  Disc3,
  DoorOpen,
  Drama,
  Droplets,
  Dumbbell,
  Ellipsis,
  Flag,
  FileText,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  Globe2,
  GraduationCap,
  HandCoins,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  Hammer,
  Headphones,
  IceCreamBowl,
  KeyRound,
  Landmark,
  Laptop,
  Lightbulb,
  Leaf,
  Martini,
  Monitor,
  Mountain,
  Music2,
  Package,
  Paintbrush,
  Palmtree,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Popcorn,
  PartyPopper,
  Plane,
  Receipt,
  ReceiptText,
  Radio,
  Repeat2,
  RotateCcw,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Sailboat,
  Scissors,
  Ship,
  ShowerHead,
  Smartphone,
  Stethoscope,
  Store,
  Soup,
  SquareParking,
  Tags,
  TentTree,
  Ticket,
  TrainFront,
  TramFront,
  Tv,
  Trophy,
  Umbrella,
  Unplug,
  Utensils,
  UsersRound,
  UtilityPole,
  WalletCards,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Wrench,
} from 'lucide-react'
import type { CategoryColorKey, CategoryIconKey } from './api'

const icons: Record<CategoryIconKey, ComponentType<{ className?: string; 'aria-hidden'?: boolean }>> = {
  house: House,
  landmark: Landmark,
  'repeat-2': Repeat2,
  dumbbell: Dumbbell,
  cigarette: Cigarette,
  flag: Flag,
  'heart-handshake': HeartHandshake,
  'graduation-cap': GraduationCap,
  clapperboard: Clapperboard,
  gift: Gift,
  shirt: Shirt,
  smartphone: Smartphone,
  'heart-pulse': HeartPulse,
  'shopping-basket': ShoppingBasket,
  plane: Plane,
  'party-popper': PartyPopper,
  'tram-front': TramFront,
  'receipt-text': ReceiptText,
  utensils: Utensils,
  'briefcase-business': BriefcaseBusiness,
  'car-front': CarFront,
  ellipsis: Ellipsis,
  'banknote-arrow-up': BanknoteArrowUp,
  'rotate-ccw': RotateCcw,
  'circle-plus': CirclePlus,
  'hand-coins': HandCoins,
  tags: Tags,
  'wallet-cards': WalletCards,
  'bed-double': BedDouble,
  'building-2': Building2,
  'key-round': KeyRound,
  wifi: Wifi,
  flame: Flame,
  lightbulb: Lightbulb,
  droplets: Droplets,
  tv: Tv,
  'music-2': Music2,
  'gamepad-2': Gamepad2,
  'book-open': BookOpen,
  laptop: Laptop,
  camera: Camera,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  martini: Martini,
  'bus-front': BusFront,
  'train-front': TrainFront,
  bike: Bike,
  fuel: Fuel,
  wrench: Wrench,
  'shopping-cart': ShoppingCart,
  store: Store,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'badge-dollar-sign': BadgeDollarSign,
  'circle-dollar-sign': CircleDollarSign,
  receipt: Receipt,
  hospital: Hospital,
  pill: Pill,
  stethoscope: Stethoscope,
  baby: Baby,
  'users-round': UsersRound,
  heart: Heart,
  handshake: Handshake,
  phone: Phone,
  package: Package,
  hotel: Hotel,
  'alarm-clock': AlarmClock,
  archive: Archive,
  armchair: Armchair,
  bath: Bath,
  'bell-ring': BellRing,
  bolt: Bolt,
  'calendar-days': CalendarDays,
  'chart-pie': ChartPie,
  'chef-hat': ChefHat,
  'circle-gauge': CircleGauge,
  'clipboard-list': ClipboardList,
  'cloud-sun': CloudSun,
  coins: Coins,
  'cooking-pot': CookingPot,
  crown: Crown,
  'disc-3': Disc3,
  'door-open': DoorOpen,
  drama: Drama,
  'file-text': FileText,
  footprints: Footprints,
  'globe-2': Globe2,
  hammer: Hammer,
  headphones: Headphones,
  'ice-cream-bowl': IceCreamBowl,
  leaf: Leaf,
  monitor: Monitor,
  mountain: Mountain,
  paintbrush: Paintbrush,
  palmtree: Palmtree,
  popcorn: Popcorn,
  radio: Radio,
  sailboat: Sailboat,
  scissors: Scissors,
  ship: Ship,
  'shower-head': ShowerHead,
  soup: Soup,
  'square-parking': SquareParking,
  'tent-tree': TentTree,
  ticket: Ticket,
  trophy: Trophy,
  umbrella: Umbrella,
  unplug: Unplug,
  'utility-pole': UtilityPole,
  'washing-machine': WashingMachine,
  waves: Waves,
  wine: Wine,
}

export function CategoryIcon({ iconKey, colorKey, className = '' }: { iconKey: CategoryIconKey; colorKey: CategoryColorKey; className?: string }) {
  const Icon = icons[iconKey]
  return <Icon className={`category-icon color-key--${colorKey} ${className}`.trim()} aria-hidden />
}

export function categoryIconLabel(iconKey: CategoryIconKey) {
  return {
    house: 'Dům', landmark: 'Banka', 'repeat-2': 'Opakování', dumbbell: 'Činka', cigarette: 'Cigareta', flag: 'Vlajka',
    'heart-handshake': 'Dar', 'graduation-cap': 'Vzdělávání', clapperboard: 'Zábava', gift: 'Dárek', shirt: 'Oblečení',
    smartphone: 'Elektronika', 'heart-pulse': 'Zdraví', 'shopping-basket': 'Nákup', plane: 'Dovolená', 'party-popper': 'Párty',
    'tram-front': 'MHD', 'receipt-text': 'Účty', utensils: 'Restaurace', 'briefcase-business': 'Práce', 'car-front': 'Auto',
    ellipsis: 'Ostatní', 'banknote-arrow-up': 'Výplata', 'rotate-ccw': 'Refundace', 'circle-plus': 'Extra příjem',
    'hand-coins': 'Peníze', tags: 'Prodej', 'wallet-cards': 'Peněženka',
    'bed-double': 'Ložnice', 'building-2': 'Budova', 'key-round': 'Klíče', wifi: 'Internet', flame: 'Energie', lightbulb: 'Světlo',
    droplets: 'Voda', tv: 'Televize', 'music-2': 'Hudba', 'gamepad-2': 'Hry', 'book-open': 'Knihy', laptop: 'Počítač', camera: 'Fotoaparát',
    coffee: 'Kavárna', pizza: 'Jídlo', beer: 'Pivo', martini: 'Bar', 'bus-front': 'Autobus', 'train-front': 'Vlak', bike: 'Kolo',
    fuel: 'Palivo', wrench: 'Opravy', 'shopping-cart': 'Košík', store: 'Obchod', 'credit-card': 'Karta', 'piggy-bank': 'Úspory',
    'chart-no-axes-combined': 'Investice', 'badge-dollar-sign': 'Bonus', 'circle-dollar-sign': 'Peníze', receipt: 'Účtenka',
    hospital: 'Nemocnice', pill: 'Léky', stethoscope: 'Lékař', baby: 'Dítě', 'users-round': 'Lidé', heart: 'Srdce', handshake: 'Dohoda',
    phone: 'Telefon', package: 'Balík', hotel: 'Hotel',
    'alarm-clock': 'Budík', archive: 'Archiv', armchair: 'Křeslo', bath: 'Koupel', 'bell-ring': 'Oznámení', bolt: 'Elektřina',
    'calendar-days': 'Kalendář', 'chart-pie': 'Graf', 'chef-hat': 'Vaření', 'circle-gauge': 'Měřič', 'clipboard-list': 'Seznam',
    'cloud-sun': 'Počasí', coins: 'Mince', 'cooking-pot': 'Vaření', crown: 'Koruna', 'disc-3': 'Disk', 'door-open': 'Dveře',
    drama: 'Divadlo', 'file-text': 'Dokument', footprints: 'Chůze', 'globe-2': 'Svět', hammer: 'Kladivo', headphones: 'Sluchátka',
    'ice-cream-bowl': 'Zmrzlina', leaf: 'Příroda', monitor: 'Monitor', mountain: 'Hory', paintbrush: 'Malování', palmtree: 'Palma',
    popcorn: 'Kino', radio: 'Rádio', sailboat: 'Loď', scissors: 'Nůžky', ship: 'Loď', 'shower-head': 'Sprcha', soup: 'Polévka',
    'square-parking': 'Parkování', 'tent-tree': 'Kemp', ticket: 'Vstupenka', trophy: 'Trofej', umbrella: 'Deštník', unplug: 'Odpojení',
    'utility-pole': 'Sítě', 'washing-machine': 'Pračka', waves: 'Vlny', wine: 'Víno',
  }[iconKey]
}

export function CategoryIconPreview({ iconKey }: { iconKey: CategoryIconKey }) {
  const Icon = icons[iconKey]
  return <Icon aria-hidden />
}
